updated generateExportEntry to pass node for additional logic downstream
css-modules/postcss-modules-scope pull request #55
Opened 2023-09-26 15:31 UTC by koga73

exposed the node in generateExportEntry so downstream logic can be written to determine if the node is a class or id

2023-12-20 16:46 UTC, koga73 commented
Bump - can someone please review and merge this?
Thank you!

2023-12-20 17:23 UTC, alexander-akait commented on package.json
> +  "version": "3.1.0",
Please avoid it in this PR, it will be generate automatically

2023-12-20 17:24 UTC, alexander-akait requested changes
Fix the problem above, thank you

2023-12-20 17:52 UTC, koga73 commented
Complete, reverted package.json version

2023-12-21 13:02 UTC, alexander-akait approved these changes

2023-12-21 13:03 UTC, merged